# --- General options --- #

title: CoffeeCode
description: Sito ufficiale del gruppo 17 - CoffeeCode
author: Gruppo 17

# --- Navigation bar options --- #

navbar-links:
  Home: "index"
  Revisioni: "revisioni"
  Contatti: "contatti"

avatar: "/img/logo.jpg"

# --- Background colour/image options --- #

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Misc --- #

# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
title-separator: "|"

# Ruby Date Format
date_format: "%B %-d, %Y"

markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

plugins:
  - jekyll-paginate
  - jekyll-sitemap
